# Note: Use scripts/runDockerSimulation.sh to make sure all environment variables are set

services:
  simulator:
    image: ${SUMATRA_IMAGE_SIMULATOR:-sumatra:latest}
    command: "-hl --moduli sim_server --autoRef --maxSpeed --initialCommand PREPARE_KICKOFF_BLUE --waitForAis --playingTime ${SUMATRA_TARGET_STAGE_TIME:-0} --timeout ${SUMATRA_TIMEOUT:-0} ${SUMATRA_SIMULATOR_ADDITIONAL_ARGS:-}"
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - "./temp/${PROJECT_NAME}/simulator/build:/Sumatra/build"
      - "./temp/${PROJECT_NAME}/simulator/data:/Sumatra/data"
    networks:
      - default

  ai-yellow:
    image: ${SUMATRA_IMAGE_YELLOW:-sumatra:latest}
    command: "-hl --moduli sim_client --host simulator --aiYellow ${SUMATRA_AI_ADDITIONAL_ARGS:-}"
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      - SUMATRA_INFLUX_DB_URL=${SUMATRA_INFLUX_DB_URL:-http://influxdb:8086}
      - SUMATRA_INFLUX_DB_PASSWORD=${SUMATRA_INFLUX_DB_PASSWORD:-}
      - SUMATRA_INFLUX_DB_USERNAME=${SUMATRA_INFLUX_DB_USERNAME:-}
    volumes:
      - "./temp/${PROJECT_NAME}/yellow/data:/Sumatra/data"
    networks:
      - default
      - sumatra_stats_statistics

  ai-blue:
    image: ${SUMATRA_IMAGE_BLUE:-sumatra:latest}
    command: "-hl --moduli sim_client --host simulator --aiBlue ${SUMATRA_AI_ADDITIONAL_ARGS:-}"
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      - SUMATRA_INFLUX_DB_URL=${SUMATRA_INFLUX_DB_URL:-http://influxdb:8086}
      - SUMATRA_INFLUX_DB_PASSWORD=${SUMATRA_INFLUX_DB_PASSWORD:-}
      - SUMATRA_INFLUX_DB_USERNAME=${SUMATRA_INFLUX_DB_USERNAME:-}
    volumes:
      - "./temp/${PROJECT_NAME}/blue/data:/Sumatra/data"
    networks:
      - default
      - sumatra_stats_statistics

networks:
  sumatra_stats_statistics:
    external: true
